language: java

jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
      - chengwu@tencent.com
      - iainyu@tencent.com
      - yongqingliu@tencent.com
      - wjielai@tencent.com
      - fysntian@tencent.com
    on_success: always # default: change
    on_failure: always # default: always
  
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true

dist: trusty

script: travis_wait 90 mvn test -Dtest=com.qcloud.cos.SuiteTest

